name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04, ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4

    - name: "setup linux build environment"
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev libutempter-dev autoconf automake nettle-dev

    - name: "setup macos build environment"
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: brew install protobuf automake

    - name: "generate build scripts"
      run: ./autogen.sh

    - name: "configure"
      run: ./configure --enable-compile-warnings=error

    - name: "build"
      run: make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)

    - name: "test"
      run: make check
